name: Build PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install LaTeX
      run: sudo apt-get install -y texlive-latex-extra texlive-fonts-extra

    - name: build pdf
      run: pdflatex src/resume-en.tex

    - uses: actions/upload-artifact@v3
      with:
        name: my_resume.pdf
        path: resume-en.pdf
