name: Build PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: xu-cheng/latex-action@v2
      with:
        root_file: src/resume-en.tex
    - uses: actions/upload-artifact@v3
      with:
        name: my_resume.pdf
        path: src/resume-en.pdf
#    - uses: actions/download-artifact@v3
#      with:
#        name: my_resume.pdf
#        path: src/resume-en.pdf
#    - name: Display structure of downloaded files
#      run: ls -R
