name: Create release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-latex-extra texlive-fonts-extra

      - name: build pdf
        run: pdflatex src/resume-en.tex

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: resume-en.pdf
